import dao.BookDao;
import dao.EntityManagerAdmin;
import models.Book;

public class Main {

        public static void main(String[] args) {
            BookDao bookDao = new BookDao();

            // Create a new Book instance
            Book book = new Book();
            book.setTitle("Don Quixote");
            book.setAuthor("Miguel de Cervantes");
            book.setPublicationYear(1605);
            book.setAvailable(true);

            // Save the book to the database
            bookDao.save(book);
            System.out.println("Book saved: " + book);

            // Retrieve the book by ID (assuming ID is autogenerated and you want to fetch it after saving)
            Book retrievedBook = bookDao.getBook(book.getId());
            System.out.println("Retrieved Book: " + retrievedBook);

            // Update the book's title
            retrievedBook.setTitle("The Ingenious Gentleman Don Quixote of La Mancha");
            bookDao.update(retrievedBook);
            System.out.println("Updated Book: " + retrievedBook);

            // Delete the book
            bookDao.delete(retrievedBook);
            System.out.println("Book deleted: " + retrievedBook);

            // Close the EntityManager to release resources
            EntityManagerAdmin.close();
        }
    }

